### ISSUE TITLE
InvalidCastException when using Any or Contains on nested array

### ISSUE THREAD

**Issue by JuliusMikkela** [redis/redis-om-dotnet#284] opened 2023-01-03 14:49 UTC
I have a setup where object A contains an array of object B, which in turn has an array of strings (or other primitives).

When I query the nested B's for a value, I get an InvalidCastException back like:

Unable to cast object of type 'System.Linq.Expressions.MethodCallExpression2' to type 'System.Linq.Expressions.BinaryExpression'.

I've tried tweaking the query and the models, and re-reading the docs, but I can't find a way to pass the expression down. 

Full code:

```csharp
using Redis.OM;
using Redis.OM.Modeling;
using StackExchange.Redis;

var connection = new RedisConnectionProvider(ConfigurationOptions.Parse("localhost:6379"));

// connection.Connection.DropIndex(typeof(TypeA));

connection.Connection.CreateIndex(typeof(TypeA));

connection.RedisCollection<TypeA>().Insert(new TypeA(1, new[] { new TypeB(2, new[] { "foo", "bar" }), new TypeB(3, new[] { "fob" }) }));
connection.RedisCollection<TypeA>().Insert(new TypeA(3, new[] { new TypeB(4, new[] { "foo", "bar" }), new TypeB(5, new[] { "baf" }) }));

var res = connection.RedisCollection<TypeA>()
    .Where(x => x.TypeBs.Any(y => y.Values.Contains("foo")))
    .ToList();

res.ForEach(x => Console.WriteLine($"{x}: {string.Join(" | ", x.TypeBs.SelectMany(y => $"{y.Id} ~ {string.Join(" + ", y.Values)}"))}"));

Console.ReadLine();

[Document(StorageType = StorageType.Json, Prefixes = new[] { "typeA" }, IndexName = "idx:typeA")]
public record TypeA([property: RedisIdField, Indexed] int Id, [property: Indexed] TypeB[] TypeBs);

public record TypeB([property: RedisIdField, Indexed] int Id, string[] Values);
```

**Comment by Dreadheart** [comment] 2023-01-03 15:00
And for clarification, it's not an issue caused by the double array; the same happens if TypeB is queried equivalently like:

```csharp
var ids = new[] { 2 };

var res = connection.RedisCollection<TypeA>()
    .Where(x => x.TypeBs.Any(y => ids.Contains(y.Id)))
    .ToList();
```

**Comment by cherry3** [comment] 2023-03-08 15:13
What is the solution? I'm also trying to filter based on a value in a nested array with complex types.

**Comment by zulander1** [comment] 2023-03-14 09:47
> What is the solution? I'm also trying to filter based on a value in a nested array with complex types.

I think an easy fix, would be to rearrange your model if possible

**Comment by AndersenGans** [comment] 2023-04-12 08:13
@zulander1 could u please explain what do u mean by rearrange? I also have the same problem. My document contains array of values (tags) and I receive an array of values to filter on. how do u propose to manage this?

**Comment by zulander1** [comment] 2023-04-12 12:22
@AndersenGans for this example i would re-arrange it like this, you will probably need to do two lookups but this would work..

public record TypeB([property: RedisIdField, Indexed] int Id, string[] Values, int TypeAId);

 fyi didn't test it

**Comment by AndersenGans** [comment] 2023-04-12 14:45
just trying to make my issue as clear as possible, arrays of primitive types, require .Any() method but no luck so far, what would u suggest in this case then?
![image](https://user-images.githubusercontent.com/25801509/231494231-e70b9c58-ff7e-4e3d-a085-56100518d8f4.png)

**Comment by zulander1** [comment] 2023-04-12 14:53
try this:

var documents = await connection.RedisCollection<TestDocument>()
.AnyAsync(x => x.AuthOptions.Contains("test"));// exception Unable to cast object of type 'System.Linq.Expressions.MethodCallExpressionN' to type 'System.Linq.Expressions.BinaryExpression'

**Comment by AndersenGans** [comment] 2023-04-12 15:02
but this wouldn't allow me to search by multiple possible values for tag field? like if I want to search whether AuthOptions field contains "Contactless" or "SMS" or whatever else as well. it is only possible to check for one specific value?

**Comment by AndersenGans** [comment] 2023-04-12 15:05
in Redis its possible to do like this:
`FT.SEARCH idx-Test "@random_tag_field:{option1 | option2 | option3}"`
could u provide how is it possible to do same with Redis.OM?

**Comment by zulander1** [comment] 2023-04-12 15:26
> in Redis its possible to do like this: `FT.SEARCH idx-Test "@random_tag_field:{option1 | option2 | option3}"` could u explain how is it possible to do same with Redis.OM?

it is possible but it's bug.. with the query phaser ..

**Comment by AndersenGans** [comment] 2023-04-12 15:33
> > in Redis its possible to do like this: `FT.SEARCH idx-Test "@random_tag_field:{option1 | option2 | option3}"` could u explain how is it possible to do same with Redis.OM?
> 
> it is possible but it's bug.. with the query phaser ..

just out of curiosity - is it somewhere in your backlog already? 🙂

**Comment by zulander1** [comment] 2023-04-12 15:46
@slorello89 can help answer that!

**Comment by slorello89** [comment] 2023-08-16 12:55
closing this out to tidy up

**Closed by slorello89** 2023-08-16 12:55 UTC
Labels: question
