### ISSUE TITLE
Exception is trown depending on which Project a query is run in

### ISSUE THREAD

**Issue by PeterZbinden** [redis/redis-om-dotnet#104] opened 2022-05-09 00:24 UTC
I currently face the following isse: When using queries defined in a baseclass in a shared library (.NET 6), I get the following Exception: 
`System.InvalidOperationException
Could not retrieve value from Id, most likely, it is not properly decorated in the model defining the index.
   at Redis.OM.Common.ExpressionParserUtilities.GetOperandStringForMember(MemberExpression member)
   at Redis.OM.Common.ExpressionParserUtilities.GetOperandStringForQueryArgs(Expression exp)
   at Redis.OM.Common.ExpressionTranslator.TranslateBinaryExpression(BinaryExpression binExpression)
   at Redis.OM.Common.ExpressionTranslator.BuildQueryFromExpression(Expression exp)
   at Redis.OM.Common.ExpressionTranslator.BuildQueryFromExpression(Expression expression, Type type)
   at Redis.OM.Searching.RedisCollection`1.FirstOrDefaultAsync(Expression`1 expression)
   at RedisBase.Shared.Get[TRedisDbEntity](String id) in G:\Dev\RedisJsonErrorTest\RedisBase\Shared.cs:line 0
   at RedisJsonErrorTest.Sample.UsingSharedQueryThrows() in G:\Dev\RedisJsonErrorTest\RedisJsonErrorTest\Sample.cs:line 19
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90`

However the class in question is properly annotated when compared to the Tutorials etc:
`
[Document(StorageType = StorageType.Json)]
public class User : IIdentifiable
{
    [Indexed]
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
}`

This is the query in question:
`var existing = await collection.FirstOrDefaultAsync(e => e.Id == id);`

After going back and forth trying to debug the issue, I then at some point tried executing the exact same query from within in a different Project (also .NET 6), and now the Exception does not get thrown.

This was quite a headache as I was suspecting something is going wrong in my own code but I was now able reproduce the behaviour in a sample, which I attached as a zip.

[RedisJsonErrorTest.zip](https://github.com/redis/redis-om-dotnet/files/8648070/RedisJsonErrorTest.zip)

**Comment by slorello89** [comment] 2022-05-16 12:30
Hi @PeterZbinden - this is a pretty interesting, looks like it has to do with how c# handles inheritance vs implementation. So the issue is that Redis OM needs to use the property decorations (`Indexed` in this example) to determine how it's going to build the query for the item you're asking for.

In the example you sent, you are trying to perform the query on an `IIdentifiable` via constraint, even though you are using a generic, by adding the IIdentifiable constraint to the type, you are preferencing that type over the actual type. Since IIdentifiable's `Id` property lacks an `Indexed` attribute, it fails to parse it out and consequentially refuses to build the query.

So you can solve this by adding an `Indexed` attribute to `IIdentifiable.Id`. This forces you to duplicate some code (for some reason if you simply swap the attribute between the fields it doesn't look like your `User` class will honor it - this might be because it's an interface)

Something interesting I found in this case is that if `IIdentifiable` becomes an abstract class rather than an interface, you can declare the `Id` as abstract and `Indexed`, and THAT will trickle down to the child-classes, preventing you from needing to duplicate the Indexed attribute.

**Comment by slorello89** [comment] 2022-06-07 17:30
Think I've addressed the issue with my comment @PeterZbinden - so I'm going to close this, feel free to reopen if not.

**Closed by slorello89** 2022-06-07 17:30 UTC
