### ISSUE TITLE
When saving a nested item using SaveAsync (with state tracking error) getting an error

### ISSUE THREAD

**Issue by rajasekarshanmugam** [redis/redis-om-dotnet#269] opened 2022-12-08 06:27 UTC
We are using Redis JSON (moved from Hash to JSON model recently) and need to update a child record field. However, when the child record is modified and saved, there is an error during SaveAsync.

StackExchange.Redis.RedisServerException: 'ERR Error running script (call to f_cbbf1c4fab5064f419e469cc51c563f8bf51e6fb): @user_script:5: WRONGTYPE wrong type of path value - expected scalar but found {    "Id": "item1",    "Name": "item1"  }'

Below is a repro code using top-level statements. Error is thrown on Save/SaveAsync call. Only a single property has to be updated in the child record, is there any other way to do this? Direct JSONSet might help too, but wanted to avoid that when possible.

`
using Redis.OM;
using Redis.OM.Modeling;
using StackExchange.Redis;

var cm = ConnectionMultiplexer.Connect("host.docker.internal:6379");
var provider = new RedisConnectionProvider(cm);

var w1 = new Item { Id = "item1", Name = "item1", };
var w2 = new Item { Id = "item2", Name = "item2", };

var o1 = new OrderTest
{
	Id = "111",
	Items = new List<Item> { w1, w2 },
};

provider.RedisCollection<OrderTest>().Insert(o1);

var orders = provider.RedisCollection<OrderTest>(true);
var o2 = orders.FindById(o1.Id);
o2.Items[0].Name = o2.Items[0].Name + ".1";

orders.Save(); // throws error

//-------------- POCO
[Document(StorageType = StorageType.Json, Prefixes = new[] { "OrderTest" })]
public sealed partial class OrderTest
{
	[RedisIdField]
	public string Id { get; set; }

	[RedisField]
	[Indexed(CascadeDepth = 2)]
	public List<Item> Items { get; set; } = new();
}

public sealed partial class Item
{
	[RedisField]
	public string Id { get; set; }

	[RedisField]
	public string? Name { get; set; }
}

`

**Comment by Jeevananthan-23** [comment] 2022-12-09 14:30
Hi @rajasekarshanmugam , I this your code smell bad and see the below example which is passing successfully.

**Models**

```csharp
 [Document(StorageType = StorageType.Json, IndexName = "person-idx")]
    public partial class Person
    {
        [RedisIdField]
        [Indexed]
        public string Id { get; set; }
        public List<Address> Addresses { get; set; }
      }

 [Document(IndexName = "address-idx", StorageType = StorageType.Json)]
    public partial class Address
    {
        [Indexed] public string City { get; set; }
        [Indexed] public string State { get; set; }
        [Indexed(CascadeDepth = 1)] 
        public Address ForwardingAddress { get; set; }
        [Indexed] public GeoLoc? Location { get; set; }
        [Indexed] public Guid? Guid { get; set; }
    }
```
**Passing Test**
```CSharp
 public void TestEmbededMultipleList()
        {
            var currentAddress = new Address { State = "TN" , City = "Chennai"};
            var permanetAddress = new Address { State = "TN", City = "Attur" };
            var person = new Person { Name = "Jeeva", Addresses = new List<Address> { currentAddress, permanetAddress } };
            var collection = new RedisCollection<Person>(_connection);
            collection.Insert(person);
            var person1 = collection.FindById(person.Id);
            person1.Addresses[0].State= person1.Addresses[0].State+"_state";
            collection.Save();
/*            var result = collection.Where(x=> x.Addresses[0].State == "TN_state").ToList();
            Assert.True(person.Name.Equals(result.First().Name));*/
        }
```

**Comment by rajasekarshanmugam** [comment] 2022-12-10 02:38
Thank you for the note. However, unclear what code smell is about, it's a too broader term and specifics would help.

In any case, tried the sample. After fixing a compilation error (Name is not defined), getting the same error on save. changed the line to compile - var collection = provider.RedisCollection<Person>();

![image](https://user-images.githubusercontent.com/5011723/206824457-c948022b-fc38-474d-8a03-8ab4e93a487b.png)

below are the package versions:
<PackageReference Include="StackExchange.Redis" Version="2.6.80" />
<PackageReference Include="Redis.OM" Version="0.3.1" />

redis_version:6.2.6
official latest docker image

.NET 7

Anything i am missing?

**Comment by Jeevananthan-23** [comment] 2022-12-10 04:20
Can you share me the monitor logs of `redis-cli` and are you using `redis-om` package and so `Redis_server_stack`docker file or only the `RedisSearch` module ?

**Comment by rajasekarshanmugam** [comment] 2022-12-10 13:26
Below is the captured profile logs, specific error does not show up in the profile, captured them via debugger and have copied those values:


Profiled Commands on Redis
----------------------------------------------------------------------------------------------------------------------------------------

INFO replication
INFO server
GET __Booksleeve_TieBreak
ECHO "nP\xb9:\x0f\xde\x13F\xa1\x94\x12w\xf6S\x80\xbc"
ECHO "nP\xb9:\x0f\xde\x13F\xa1\x94\x12w\xf6S\x80\xbc"
SUBSCRIBE __Booksleeve_MasterChanged
INFO replication
JSON.SET Person:01GKY2P6R06V955C43W7MP41FS "." "{\"Id\":\"01GKY2P6R06V955C43W7MP41FS\",\"Addresses\":[{\"City\":\"Chennai\",\"State\":\"TN\"},{\"City\":\"Attur\",\"State\":\"TN\"}]}"
SELECT 0
JSON.GET Person:01GKY2P6R06V955C43W7MP41FS "."
SELECT 0

Debugger watch - error command and args
----------------------------------------------------------------------------------------------------------------------------------------
command	"EVALSHA"	string
args	{string[9]}	string[]
[0]	"cbbf1c4fab5064f419e469cc51c563f8bf51e6fb"	string
[1]	"1"	string
[2]	"Person:01GKY2P6R06V955C43W7MP41FS"	string
[3]	"ARRAPPEND"	string
[4]	"$.Addresses"	string
[5]	"'{\r\n  \"City\": \"Chennai\",\r\n  \"State\": \"TN_state\"\r\n}'"	string
[6]	"ARRREM"	string
[7]	"$.Addresses"	string
[8]	"'{\r\n  \"City\": \"Chennai\",\r\n  \"State\": \"TN\"\r\n}'"	string

Package Details:

PackageReference Include="NReJSON" Version="4.0.0"
PackageReference Include="Redis.OM" Version="0.3.1"

using a docker compose, below is the service entry:
  redis:
    image: redislabs/redismod:latest
    profiles:
      - "dbs"
      - "all"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

please let know if any more details are needed.

**Comment by Jeevananthan-23** [comment] 2022-12-10 20:49
As of now I figured out that the issue is there with `JSON.ARRINDEX` and this throws the error in cli let me check more. I think the issue might the serialization of `Json object` but we are search for index of `array`. This make sense.

**Comment by slorello89** [comment] 2022-12-12 13:09
This is a duplicate of #171 - will need to look into it.

**Closed** 2023-02-03 12:11 UTC
