### ISSUE TITLE
 ERR Error running script : @user_script:5: WRONGTYPE wrong type of path value - expected scalar but found

### ISSUE THREAD

**Issue by MostafaSDesoky** [redis/redis-om-dotnet#376] opened 2023-05-09 07:23 UTC
Hello
I've an error and I don't know if it was because of having single quotation inside double quotation or not
the error
```
System.Exception: ERR Error running script (call to f_cbbf1c4fab5064f419e469cc51c563f8bf51e6fb): @user_script:5: WRONGTYPE wrong type of path value - expected scalar but found {    "Name": "Control Room",    "Note": "'D7D( E*'.1 'C+1 EF 10 /B'&B ",    "DateTime": "2023-05-07T10:13:00.537Z"  }
Failed on EVAL local key = KEYS[1]
local num_args = table.getn(ARGV)
for i=1, num_args, 3 do
    if 'ARRREM' == ARGV[i] then
        local index = redis.call('JSON.ARRINDEX', key, ARGV[i+1], ARGV[i+2])[1]
        if index>=0 then
            redis.call('JSON.ARRPOP', key, ARGV[i+1], index)
        end
    else
        if 'DEL' == ARGV[i] then
            redis.call('JSON.DEL',key,ARGV[i+1])
        else
            redis.call(string.format('JSON.%s', ARGV[i]), key, ARGV[i+1], ARGV[i+2])
        end
    end
end
 1 Task:a9fbfa07-0779-4c75-9750-0d8f7ad4ed67 SET $.ShiftDate 1683072000000 SET $.PlacedDate 1683106835000 SET $.PickupPlannedTime 1683115238361 SET $.DropoffPlannedTime 1683118838361 SET $.ReadyTime 1683115238361 SET $.LastSynchedDate 1683454433111 ARRAPPEND $.NoteAction {
  "Name": "Control Room",
  "Note": "الطلب متاخر اكثر من 10 دقائق ",
  "DateTime": 1683454380537
} ARRAPPEND $.NoteAction {
  "Name": "Bashayer",
  "Note": "الطلب متاخر ",
  "DateTime": 1683454432603
} ARRREM $.NoteAction {
  "Name": "Control Room",
  "Note": "الطلب متاخر اكثر من 10 دقائق ",
  "DateTime": "2023-05-07T10:13:00.537Z"
} ARRREM $.NoteAction {
  "Name": "Bashayer",
  "Note": "الطلب متاخر ",
  "DateTime": "2023-05-07T10:13:52.603Z"
} SET $.CreatedDate 1683104438361 SET $.UpdatedDate 1683104438993
 ---> StackExchange.Redis.RedisServerException: ERR Error running script (call to f_cbbf1c4fab5064f419e469cc51c563f8bf51e6fb): @user_script:5: WRONGTYPE wrong type of path value - expected scalar but found {    "Name": "Control Room",    "Note": "'D7D( E*'.1 'C+1 EF 10 /B'&B ",    "DateTime": "2023-05-07T10:13:00.537Z"  }
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1886
   at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection`1 args, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1516
   at Redis.OM.RedisConnection.Execute(String command, String[] args)
   --- End of inner exception stack trace ---
   at Redis.OM.RedisConnection.Execute(String command, String[] args)
   at Redis.OM.RedisCommands.CreateAndEval(IRedisConnection connection, String scriptName, String[] keys, String[] argv, String fullScript)
   at Redis.OM.Searching.RedisCollection`1.Save()
   at Roboost.Kernel.Redis.Services.Tasks.TaskService.DeleteBulkWithoutTenant(IEnumerable`1 taskIDs)
   at Roboost.Dispatching.API.Services.Features.Tasks.Commands.AutoUpdateTaskRedisCommandHandler.Handle(AutoUpdateTaskRedisCommand request, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at Roboost.Dispatching.API.Controllers.Task.TaskController.AutoUpdateTaskRedisCommand()
   at lambda_method1203(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Roboost.Dispatching.API.Filters.ErrorHandlingMiddleware.Invoke(HttpContext context)
```

this when trying to add model task to redis

task model
```
public class Task : BaseModel, IActive, IDelete
    {
        public Task()
        {
            NoteAction = new List<RedisTaskNoteViewModel>();
        }

        public List<RedisTaskNoteViewModel>? NoteAction { get; set; }
}
```

```
    public class RedisTaskNoteViewModel
    {
        public string Name { get; set; }
        public string Note { get; set; }
        public DateTime DateTime { get; set; }
    }
```

**Comment by slorello89** [comment] 2023-05-09 17:05
I believe this is due to an old issue that we validated was working now in #285 - what version of RediSearch/Redis Stack are you using? Try upgrading to the latest version and see if that resolves it.

**Comment by MostafaSDesoky** [comment] 2023-05-14 09:21
My redis version is 0.4.2

**Comment by slorello89** [comment] 2023-05-14 10:57
That's the version of the client software. I think the issue is the servers software version.

**Comment by MostafaSDesoky** [comment] 2023-05-14 13:46
Okey I will ask the person that has access to the server to do so and see what will happen

**Comment by slorello89** [comment] 2023-07-27 19:58
Going to close this to tidy up - feel free to reopen if it's not an issue with the Redis Server version.

**Closed by slorello89** 2023-07-27 19:58 UTC
Labels: need-more-info
